Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2022-10, with the labels that each got.

#122 feat: import vrops user from authsource
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/iom

#124 chore: bump module version to 1.9.0.1001
  PowerValidatedSolutions.psd1
Labels: chore

#126 chore: update IAM SampleScripts to support VCF 4.5 PnP workbook
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOne.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
Labels: enhancement, chore

#131 feat: Update DRI Sample Scripts for VCF 4.5 Support
  CHANGELOG.md
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
Labels: enhancement, size/m, vvs/dri, samples

#133 feat: update iom sample scripts
  CHANGELOG.md
  SampleScripts/iom/iomConfigureVrealizeOperations.ps1
  SampleScripts/iom/iomDeployVrealizeOperations.ps1
Labels: enhancement, vvs/iom, samples

#128 feat(ila): update content pack
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: enhancement, vvs/ila

#134 fix(ila): get log forwarder by id
  PowerValidatedSolutions.psm1
Labels: bug, vvs/ila

#135 feat(ila): update log forwarder
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/ila

#137 feat: update and validation for VCF 4.5 and sample scripts
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/ila/ilaConfigureVrealizeLogInsight.ps1
  SampleScripts/ila/ilaDeployVrealizeLogInsight.ps1
  SampleScripts/iom/iomDeployVrealizeOperations.ps1
Labels: enhancement, needs-review, size/s, chore, samples

#139 feat: add sample script for private cloud automation solution deployment
  CHANGELOG.md
  SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
Labels: enhancement, needs-review, vvs/pca, samples

#142 feat(pdr): add Site Recovery Manager notifications in vRealize Operations
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleNotifications/vrops-srm-notifications.csv
Labels: feature, size/s, vvs/pdr, samples

#143 feat(iam): add sample scripts for solution interoperability
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/iam/iamSolutionInteroperability.ps1
Labels: feature, needs-review, size/s, vvs/iam, samples

#144 feat(Ila): add sample scripts for solution interoperability
  CHANGELOG.md
  SampleScripts/ila/ilaSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
Labels: feature, needs-review, size/s, vvs/ila, samples

#145 feat(iom): add sample scripts for solution interoperability
  CHANGELOG.md
  SampleScripts/iom/iomSolutionInteroperability.ps1
Labels: feature, needs-review, size/s, vvs/iom, samples

#146 fix(dri): address issues in samples
  PowerValidatedSolutions.psm1
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
Labels: bug, size/xs, vvs/dri, samples

#147 feat: Add a Function to Create a Storage Folder
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/pca

#148 feat: add check for existing supervisor cluster
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/dri

#149 Add Missing Items to PCA Sample Script
  PowerValidatedSolutions.psm1
  SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
Labels: enhancement, vvs/pca, samples

#151 Enhancements to Install-SiteRecoveryManager
  PowerValidatedSolutions.psm1
Labels: enhancement, refactor, size/s, vvs/pdr

#153 feat(pdr): Enhancements to Install-vSphereReplicationManager
  PowerValidatedSolutions.psm1
Labels: enhancement, refactor, size/s, vvs/pdr

#155 feat(pdr): Enhancements to Connect-DRSolutionTovCenter
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, refactor, size/m, vvs/pdr

#158 Add Shared Functions for vSphere Distributed port group and New Add License for Site Recovery Manager
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/pdr

#161 feat(pdr): Session Token Request Functions
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/pdr
