Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2022-09, with the labels that each got.

#77 fix: Remove duplicated, exported functions
  PowerValidatedSolutions.psm1
Labels: bug

#76 feat: Add additional metadata for PowerShell Gallery listing
  .github/icon-400px.png
  .github/icon-400px.svg
  .github/icon-85px.svg
  PowerValidatedSolutions.psd1
  README.md
Labels: documentation, enhancement, size/s

#79 docs: Update `README.md`
  README.md
Labels: documentation

#81 feat: enhance `Confirm-PSModule`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/xs

#82 chore: review and update formatting for iam functions
  PowerValidatedSolutions.psm1
Labels: chore

#83 chore: review and update formatting for iam functions
  PowerValidatedSolutions.psm1
Labels: chore

#84 docs: update `README.md`
  README.md
Labels: documentation

#85 chore: review and update formatting for pdr functions
  PowerValidatedSolutions.psm1
Labels: chore, vvs/pdr

#87 chore: review and update formatting for iom functions
  PowerValidatedSolutions.psm1
Labels: size/s, chore, vvs/iom

#89 chore: review and update formatting for pca functions
  PowerValidatedSolutions.psm1
Labels: size/xs, chore, vvs/pca

#91 chore: review and update formatting for shared functions
  PowerValidatedSolutions.psm1
Labels: size/s, chore, technical-debt, vvs/iam, vvs/pca, vvs/ila, vvs/iom

#92 refactor: resource-pool functions
  PowerValidatedSolutions.psm1
Labels: refactor, size/xs, vvs/pca

#93 feat: add `vrslcm-vsphere-integration.role` file
  vSphereRoles/vrslcm-vsphere-integration.role
Labels: enhancement, size/s, vvs/iom

#95 fix: update `Get-NsxtEdgeNode` cmdlet example
  PowerValidatedSolutions.psm1
Labels: bug, documentation

#88 feat: add vrops integration in vra
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/pca

#96 enhance: add support for srm/vr management packs
  PowerValidatedSolutions.psm1
Labels: enhancement, feature, size/s, vvs/pdr

#97 feat: enable vrli log configuration in vra
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/ila

#78 feat: add password policy manager
  SampleScripts/ppm/README.md
  SampleScripts/ppm/passwordpolicymanager.ps1
  SampleScripts/ppm/sampleConfigurationFull.json
  SampleScripts/ppm/sampleConfigurationSimple.json
Labels: enhancement, under-review, size/l, vvs/iam

#98 docs: update `./SampleScripts/ppm/README.md`
  SampleScripts/ppm/README.md
Labels: documentation

#99 docs: update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#102 fix: update module metadata
  PowerValidatedSolutions.psd1
Labels: bug, size/xs

#104 fix: correct blocking syntax on `Set-vRAvRLIConfig `
  PowerValidatedSolutions.psm1
Labels: bug, size/xs

#105 feat: install content pack for vro
  PowerValidatedSolutions.psm1
Labels: enhancement, needs-review

#106 fix: address gh-101
  PowerValidatedSolutions.psm1
Labels: bug, needs-review

#107 fix: get-vravrliconfig convertfrom-json
  PowerValidatedSolutions.psm1
Labels: bug, size/xs

#109 fix: inclusive language
  PowerValidatedSolutions.psm1
Labels: size/xs

#110 chore(repo): add `CODEOWNERS`
  CODEOWNERS
Labels: chore

#111 chore(repo): add docs issue template
  .github/ISSUE_TEMPLATE/docs.yml
Labels: chore

#112 chore(repo): add GitHub Actions
  .github/dependabot.yml
  .github/labels-issue.yml
  .github/labels-pull-requests.yml
  .github/workflows/issues.yml
  .github/workflows/lock.yml
  .github/workflows/maintainer-edit.yml
  .github/workflows/pull-requests.yml
  .github/workflows/stale.yml
Labels: chore

#120 feat: support standard Workspace ONE Access instance
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s

#119 ci(issues): disable workflow step
  .github/workflows/issues.yml
Labels: github-actions

#121 docs: update `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation, needs-review
