Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2022-08, with the labels that each got.

#20 Add New vSphere Role File for Cloud-Based Automation
  vSphereRoles/cloud-assembly-vsphere-integration.role
Labels: enhancement

#21 Fixed for vRealize with VCF 4.4.0 and 4.4.1
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, enhancement

#23 feat: Add vROPS adapter verification
  PowerValidatedSolutions.psm1
Labels: enhancement

#24 Add Cloud Extensibility Proxy (CEP) and vRealize Orchestrator Functions
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#26 fix: gh-25
  PowerValidatedSolutions.psm1
Labels: bug

#29 Added Region Blocks to Code for Easier Navigation
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#37 feat: Add support to update the vRealize Automation Integration credential in vRealize Operations Manager
  PowerValidatedSolutions.psm1
Labels: enhancement

#33 feat: Add support for downloading the Cloud Proxy and Cloud Extensibility Proxy from VMware Cloud
  PowerValidatedSolutions.psm1
Labels: enhancement

#36 feat: Add support to obtain the One Time Key for Cloud Proxy or Cloud Extensibility Proxy
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#30 feat: Add support to return the ESXi host and vCenter Server password policy
  PowerValidatedSolutions.psm1
Labels: enhancement

#31 feat: Add support to configure the ESXi password expiration policy
  PowerValidatedSolutions.psm1
Labels: enhancement

#40 feat: Add support to update placement policy for cloud zones in vRealize Automation
  PowerValidatedSolutions.psm1
Labels: enhancement

#41 refactor: update errors for `Add-SupervisorClusterLicense`
  PowerValidatedSolutions.psm1
Labels: bug

#42 chore(repo): update to issue forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: chore
