Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-07, with the labels that each got.

#285 feat: add vrslcm product support pack functions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature

#292 fix: update `Request-VcenterApiToken` for pwsh and linux
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug

#294 fix: update Initialize-WorkspaceOne for updated private api
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/s, vvs/iam

#295 feat: enhancements to iam scripts
  CHANGELOG.md
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOne.ps1
  SampleScripts/iam/iamSolutionInteroperability.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
Labels: enhancement, vvs/iam

#298 fix: support for cloud proxies in `Add-vROPSAdapterSddcHealth`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, vvs/iom

#300 fix: update automation role files
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  vSphereRoles/automation-orchestrator-vsphere-integration.role
  vSphereRoles/vra-vsphere-integration.role
  vSphereRoles/vro-vsphere-integration.role
Labels: bug, enhancement

#302 feat: update sample scripts for vcf5
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOne.ps1
  SampleScripts/iam/iamSolutionInteroperability.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
  SampleScripts/ila/ilaConfigureVrealizeLogInsight.ps1
  SampleScripts/ila/ilaDeployVrealizeLogInsight.ps1
  SampleScripts/ila/ilaSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoVrealizeLogInsight.ps1
  SampleScripts/iom/iomConfigureVrealizeOperations.ps1
  SampleScripts/iom/iomDeployVrealizeOperations.ps1
  SampleScripts/iom/iomSolutionInteroperability.ps1
  SampleScripts/pca/pcaDeployVrealizeAutomation.ps1
Labels: enhancement, vvs/iam, vvs/pca, vvs/ila, vvs/iom

#303 chore: release preparation
  .gitignore
  CHANGELOG.md
  Makefile
  docs/documentation/index.md
  docs/index.md
  docs/requirements.txt
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, chore

#304 chore: update project location
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  CHANGELOG.md
  CODEOWNERS
  CONTRIBUTING.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  README.md
  docs/community/support.md
  docs/documentation/index.md
  mkdocs.yml
Labels: chore, cla-not-required

#305 chore(gh): update github-actions
  .github/workflows/maintainer-edit.yml
  .github/workflows/pull-requests.yml
  .github/workflows/stale.yml
Labels: chore, github-actions, cla-not-required

#306 chore(gh): add to project
  .github/workflows/project.yml
Labels: chore, github-actions, cla-not-required

#307 feat: add vrslcm api functions and hcx role file
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  vSphereRoles/hcx-vsphere-integration.role
Labels: cla-not-required
