Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-01, with the labels that each got.

#187 feat: add json output to password policy manager
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/iam

#188 docs: update `README.md`
  README.md
Labels: documentation

#189 fix: nsxmanager account lockout missing
  PowerValidatedSolutions.psm1
Labels: bug

#190 feat: password policy manager
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/l, vvs/iam

#192 feat: remove ppm standalone script
  PowerValidatedSolutions.psm1
  SampleScripts/ppm/README.md
  SampleScripts/ppm/passwordpolicymanager.ps1
  SampleScripts/ppm/sampleConfigurationFull.json
  SampleScripts/ppm/sampleConfigurationSimple.json
Labels: enhancement, size/s, vvs/iam

#193 feat: add wsa to ppm report
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/iam

#194 feat: add wsa to remediation function
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iam

#195 feat: update wsa ppm default values
  PowerValidatedSolutions.psm1
Labels: enhancement, size/xs, vvs/iam

#196 fix: use root password for edge node password complexity
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iam

#191 feat: add `Test-PasswordPolicyConfig`
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iam

#200 chore: release prep
  CHANGELOG.md
  LICENSE
  NOTICE
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  README.md
Labels: chore
