Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-12, with the labels that each got.

#430 feat: anti-affinity rule for ops for logs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/ila

#437 fix: error handling for invoke-iamdeployment
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iam, cla-not-required

#438 Update PowerValidatedSolutions.psm1
  PowerValidatedSolutions.psm1
Labels: vvs/iam, vvs/ila

#439 feat: add vrslcm api functions
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#440 fix: formatting issue following doc updates
  PowerValidatedSolutions.psm1
Labels: bug

#441 chore(ci): fix failing `actions/labeler`
  .github/labeler-pull-requests.yml
  .github/workflows/pull-requests.yml
Labels: dependencies, chore, github-actions, cla-not-required

#442 feat: ila deployment without wsa
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/ila/ilaConfigureAriaOperationsLogs.ps1
  SampleScripts/ila/ilaDeployAriaOperationsLogs.ps1
  SampleScripts/ila/ilaUndoAriaOperationsLogs.ps1
Labels: documentation, feature, needs-review, size/l, vvs/ila, samples, cla-not-required

#443 feat: iam deployment removing wsa
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOneAccess.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
Labels: documentation, feature, size/l, vvs/iam, samples

#444 Feature: Add support to configure vSphere Replication
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, cla-not-required

#445 feat: oneclick development
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleNotifications/aria-operations-notifications-vcf.csv
Labels: documentation, enhancement, feature, needs-review, vvs/iam, vvs/ila, samples

#446 feat: enhanced error checking for iam deployments
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, enhancement, feature, needs-review, vvs/iam

#447 Feat enhancements to ila deployment error handling
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, feature, needs-review, vvs/ila

#448 feat: add oneclick cmdlets for iom
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/iom/iomConfigureAriaOperations.ps1
  SampleScripts/iom/iomDeployAriaOperations.ps1
Labels: documentation, feature, size/l, vvs/iom, samples

#449 feat: enhance aria automation deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, needs-review, size/m, vvs/pca

#450 fix: remove wsa groups from export-iamjsonspec
  PowerValidatedSolutions.psm1
Labels: bug, needs-review, size/xs, vvs/iam, cla-not-required

#451 fix: remove check for workbook for invoke-undoiomdeployment
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, needs-review, size/xs, vvs/iom, cla-not-required

#452 feat: add support for customer connect account
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, needs-review, size/m, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#453 feat: add support for pspack update and snapshots
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#454 feat: improvements to ila & iom oneclick
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, vvs/ila, vvs/iom, cla-not-required
