Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-09, with the labels that each got.

#350 feat: add function to support creating a vcf credential
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/iom, cla-not-required

#352 feat: add vcenter server credential to aria operations
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/iom, cla-not-required

#355 chore: aria rebranding - cmdlet content
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/xl, chore, vvs/pca, vvs/ila, vvs/iom, vvs/cbl, vvs/cbo, cla-not-required

#356 chore: aria rebranding - samples
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOneAccess.ps1
  SampleScripts/iam/iamSolutionInteroperability.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
  SampleScripts/ila/ilaConfigureAriaOperationsLogs.ps1
  SampleScripts/ila/ilaDeployAriaOperationsLogs.ps1
  SampleScripts/ila/ilaSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoAriaOperationsLogs.ps1
  SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
  SampleScripts/iom/iomConfigureAriaOperations.ps1
  SampleScripts/iom/iomDeployAriaOperations.ps1
  SampleScripts/iom/iomSolutionInteroperability.ps1
  SampleScripts/pca/pcaDeployAriaAutomation.ps1
  vSphereRoles/aria-automation-assembler-vsphere-integration.role
  vSphereRoles/aria-automation-orchestrator-vsphere-integration.role
  vSphereRoles/aria-operations-for-logs-vsphere-integration.role
  vSphereRoles/aria-operations-for-networks-vsphere-integration.role
  vSphereRoles/aria-operations-vsphere-integration-actions.role
  vSphereRoles/aria-operations-vsphere-integration-metrics.role
  vSphereRoles/aria-operations-vsphere-integration.role
  vSphereRoles/aria-suite-lifecycle-vsphere-integration.role
Labels: size/m, chore, vvs/pca, vvs/ila, vvs/iom, vvs/cbl, vvs/cbo, vvs\cbn, cla-not-required

#357 chore: aria rebranding - alerts and notifications
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleNotifications/aria-operations-logs-alerts-datacenter-vcf.json
  SampleNotifications/aria-operations-logs-alerts-iom.json
  SampleNotifications/aria-operations-logs-alerts-vcf.json
  SampleNotifications/aria-operations-logs-alerts-vm-asl.json
  SampleNotifications/aria-operations-notifications-srm.csv
  SampleNotifications/aria-operations-notifications-vcf.csv
Labels: size/s, chore, vvs/ila, vvs/iom, cla-not-required

#358 chore: update issue forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/workflows/project.yml
Labels: chore, cla-not-required

#359 chore: update aria product versions for json specs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/xs, chore, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#360 chore(ci): release gha
  .github/workflows/release.yml
Labels: chore, github-actions, cla-not-required

#361 chore(ci): update tests
  .ci/pester.tests.ps1
  .github/workflows/ci-module.yml
  .github/workflows/tests.yml
Labels: chore, github-actions, cla-not-required

#363 chore: update vra version for 5.1 support
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/xs, chore, vvs/pca, cla-not-required
