Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-10, with the labels that each got.

#367 chore(ci): update tests
  .github/workflows/tests.yml
Labels: chore, cla-not-required

#370 feat: enhancements for nsx and operations for logs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/iam, vvs/ila, cla-not-required

#373 chore(ci): update actions
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: chore, cla-not-required

#376 fix: Add-vCenterGlobalPermission
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/iam/iamConfigureNsx.ps1
Labels: size/xs, vvs/iam, cla-not-required

#377 feat: add support for vrli content library ova deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/m, vvs/ila, cla-not-required

#374 fix: remove pwsh version os check
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: bug, cla-not-required

#375 chore(deps): update dependencies
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: dependencies, chore, cla-not-required

#379 fix: error adding an overlay-backed nsx segment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, vvs/dri, cla-not-required

#380 feat: deploy aria suite using vsphere content library
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/l, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#381 fix: address timing issue adding vcenter to aria suite
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, cla-not-required

#382 chore: vmware aria branding udpates
  PowerValidatedSolutions.psm1
Labels: chore, cla-not-required

#383 fix: add aria suite load balancer controller type
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/xs, vvs/iom, cla-not-required

#385 fix: error enabling Harbor Registry Service
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: cla-not-required

#387 feat: add nsx principal identity api cmdlets
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/iom, vvs/cbo, vvs\cbn, cla-not-required

#388 docs: update docs
  docs/index.md
  docs/requirements.txt
Labels: documentation, cla-not-required

#389 feat: update aria version
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: feature, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#391 docs: update support
  README.md
  docs/community/index.md
  docs/community/support.md
Labels: documentation, cla-not-required

#392 feat: add management pack
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, vvs/iom, cla-not-required
