Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-04, with the labels that each got.

#231 feat: Enhance Import-vROPSNotification
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iom

#235 chore: move password policy to new module
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: chore

#237 feat: enhancements to functions
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/iam, vvs/ila

#238 feat: add prerequisite function
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature

#240 fix: missing export `Test-VCFConnection`
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, vvs/iam

#241 fix: update `Get-GlobalPermissions` html parsing
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug

#242 chore(deps): bump module prerequisites
  PowerValidatedSolutions.psm1
  README.md
Labels: documentation, dependencies, chore

#248 chore: release preparation
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  README.md
Labels: chore

#250 feat: add support for custom version of vrs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/pca, vvs/ila, vvs/iom
