Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-06, with the labels that each got.

#266 fix: deprecated api for Add-vRLIAuthenticationGroup
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/m, vvs/ila

#267 feat: enhancement to Add-vRSLCMNtpServer
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/pdr

#260 feat: enhance `Set-NsxtManagerAuthPolicy` for NSX 4.x password complexity
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#268 docs: add mkdocs
  .github/workflows/deploy.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/assets/images/icon-color.svg
  docs/assets/images/icon-white.svg
  docs/assets/stylesheets/extra.css
  docs/community/code-of-conduct.md
  docs/community/contributing.md
  docs/community/support.md
  docs/documentation/index.md
  docs/favicon.ico
  docs/index.md
  docs/install.md
  docs/license.md
  docs/release-notes.md
  docs/requirements.txt
  docs/snippets/import-module.ps1
  docs/snippets/install-module.ps1
  docs/snippets/installed-module.ps1
  docs/snippets/update-module.ps1
  docs/snippets/update-modules.ps1
  docs/update.md
  docs/user-access.md
  mkdocs.yml
Labels: documentation, github-actions

#269 feat: add invoke command line for vcenter server
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  vSphereRoles/vcdr-vsphere-integration.role
Labels: feature

#271 feat: enhance `Set-NsxtManagerAuthPolicy` for `hash_algorithm`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#273 feat: add esxi admin group cmdlets
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s

#275 feat: VCF 5 support for vRealize Suite
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/s, vvs/pca, vvs/ila, vvs/iom

#278 feat: add new cmdlets
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s

#277 chore: release-preparation
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/pull_request_template.md
  CHANGELOG.md
  LICENSE
  NOTICE
  PowerValidatedSolutions.psd1
  docs/community/index.md
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, chore

#280 feat: add test functions connection and authentication
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement

#281 chore(gh): fix bug issue form
  .github/ISSUE_TEMPLATE/bug.yml
Labels: chore

#282 fix: update vrli api token request
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, breaking-change, vvs/ila
