Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-08, with the labels that each got.

#313 fix: address ila post-validation issues
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/xs, vvs/ila, cla-not-required

#314 feat: add nsxt functions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, cla-not-required

#317 feat: add support for vcf 452 and vrealize suite
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#324 feat: add nsxt security policy and group apis
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, cla-not-required

#325 docs: update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, cla-not-required

#326 chore: update formatting across nsx functions
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: chore, cla-not-required

#328 feat: add functions to enable vrli alerts
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleNotifications/vrli-iom-alerts.json
  SampleNotifications/vrli-vcf-alerts.json
  SampleNotifications/vrli-vrslcm-alerts.json
Labels: enhancement, size/m, vvs/ila, cla-not-required

#327 fix: issue #265
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, cla-not-required

#331 fix: issue #330
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, cla-not-required

#333 fix: replace wmi cmdlet usage with cim cmdlets
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, needs-review, cla-not-required

#335 fix: address various issues observed
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleYaml/sfo-w01-tkc01-cluster.yaml
Labels: size/s, vvs/iom, cla-not-required

#337 chore: release preparation
  CHANGELOG.md
Labels: chore, cla-not-required

#338 fix: added wait to `Connect-DRSolutionTovCenter`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, vvs/pdr, cla-not-required

#341 feat: add sudo option for chage cmds
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, cla-not-required

#342 feat: add version check based on `-subscriptionUrl`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/dri, cla-not-required

#343 feat: enhance `Add-ContentLibrary` for powershell 7
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/dri, cla-not-required

#345 feat: activate vcf management pack
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/xs, vvs/iom, cla-not-required
