Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-05, with the labels that each got.

#251 chore: rename aria automation roles
  vSphereRoles/automation-assembler-vsphere-integration.role
  vSphereRoles/automation-orchestrator-vsphere-integration.role
Labels: size/xs, chore, vvs/cba

#254 feat: add operations for networks role file
  CHANGELOG.md
  vSphereRoles/operations-for-networks-vsphere-integration.role
Labels: feature, size/xs, vvs\cbn

#252 chore: update nsx product terms
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: chore

#255 feat: adjust aria operations role file names
  CHANGELOG.md
  vSphereRoles/operations-for-logs-vsphere-integration.role
  vSphereRoles/operations-vsphere-integration.role
Labels: refactor, vvs/cbl, vvs/cbo

#256 refactor: global permissions for isolated workload domains
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: refactor, breaking-change

#257 feat: add vcf 451 support for WSA deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature

#261 fix: address missing sso domain for pre 4.5.0.0 release of VCF
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, vvs/iam

#264 feat: update vrealize versions to support 451
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/pca, vvs/iom
