Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2023-11, with the labels that each got.

#394 feat: add nsx credential in aria operations
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, vvs/iom

#393 docs: add air-gapped install
  docs/install.md
  docs/snippets/copy-module-local-linux.sh
  docs/snippets/copy-module-local-windows.ps1
  docs/snippets/import-module-local-linux.ps1
  docs/snippets/pre-req-linux.sh
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation

#401 docs: update install module with repository flag
  docs/snippets/install-module.ps1
  docs/snippets/save-module-local-linux.ps1
  docs/snippets/save-module-local-windows.ps1
Labels: documentation

#402 fix: blank credentials in get-vcenterserverdetail
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/s, vvs/iam

#403 feat: iam deploy and undo in single function
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, enhancement, size/m, vvs/iam, cla-not-required

#404 fix: remove secondary ntp from export-vropsjsonspec
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, vvs/iom

#405 feat: add nsxt identity source
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/iam

#407 feat: ila deploy and undo in single functions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, feature, size/m, vvs/ila

#408 feat: add support for nsx roles to ldap users
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/iam

#409 feat: add changed api support for ops for logs group management
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, feature, vvs/ila

#410 feat: add support for ad authentication in ops for logs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/ila, cla-not-required

#411 feat: add ldap support for nsx manager
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/m, vvs/iam, cla-not-required

#412 feat: add undo-vrliauthenticationwsa
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/s, vvs/ila

#413 feat: enhance error handling
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature

#414 feat: add support for aria suite lifecycle load balancer
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, feature, size/m, vvs/pca, vvs/iom, cla-not-required

#416 feat: add load balancer for wsa
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/s

#417 chore: code formatting for test and utility functions
  PowerValidatedSolutions.psm1
Labels: chore

#418 chore: code formatting for ad and cloud foundation functions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, chore

#419 chore: code formatting for vsphere functions
  PowerValidatedSolutions.psm1
Labels: chore

#420 chore: code formatting for wsa functions
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: chore

#424 chore: code formatting for aria automation and orchestrator functions
  PowerValidatedSolutions.psm1
Labels: chore

#415 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  PowerValidatedSolutions.psd1
  README.md
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
  SampleScripts/iam/iamConfigureNsx.ps1
  SampleScripts/iam/iamConfigureVsphere.ps1
  SampleScripts/iam/iamConfigureWorkspaceOneAccess.ps1
  SampleScripts/iam/iamSolutionInteroperability.ps1
  SampleScripts/iam/iamUndoDeployment.ps1
  SampleScripts/ila/ilaConfigureAriaOperationsLogs.ps1
  SampleScripts/ila/ilaDeployAriaOperationsLogs.ps1
  SampleScripts/ila/ilaSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoAriaOperationsLogs.ps1
  SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
  SampleScripts/iom/iomConfigureAriaOperations.ps1
  SampleScripts/iom/iomDeployAriaOperations.ps1
  SampleScripts/iom/iomSolutionInteroperability.ps1
  SampleScripts/pca/pcaDeployAriaAutomation.ps1
  docs/index.md
  mkdocs.yml
Labels: chore, cla-not-required

#425 chore: code formatting for aria operations functions
  PowerValidatedSolutions.psm1
Labels: chore

#426 chore: code formatting for aria operations for logs functions
  PowerValidatedSolutions.psm1
Labels: chore

#427 chore: code formatting for cloud functions
  PowerValidatedSolutions.psm1
Labels: chore
