Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-05, with the labels that each got.

#597 feat: certificate management
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/certificates/Invoke-GeneratePKCS12.md
  docs/documentation/functions/site-recovery-manager/Install-VamiCertificate.md
  docs/documentation/functions/site-recovery-manager/Request-VamiPKCS12Certificate.md
  docs/documentation/functions/site-recovery-manager/Test-SrmAuthenticationREST.md
  docs/documentation/functions/site-recovery-manager/Test-SrmConnection.md
  docs/documentation/functions/site-recovery-manager/Test-SrmSdkAuthentication.md
  docs/documentation/functions/solutions/pdr/index.md
  docs/documentation/functions/vsphere-replication/Install-VamiCertificate.md
  docs/documentation/functions/vsphere-replication/Request-VamiPKCS12Certificate.md
  docs/documentation/functions/vsphere-tanzu/Install-TanzuSignedCertificate.md
  mkdocs.yml
Labels: bug, documentation, enhancement, size/l, vvs/pdr, cla-not-required

#599 Feat pdr improvements
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/site-recovery-manager/Undo-SrmMapping.md
  docs/documentation/functions/vsphere-replication/Test-VrSdkAuthentication.md
  mkdocs.yml
Labels: documentation, enhancement, size/l, vvs/pdr, cla-not-required

#601 fix: Add-SrmLicenseKey failure
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/pdr, cla-not-required

#602 feat: update aria automation version and remove eogs items
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, size/xs, vvs/pca, cla-not-required

#603 feat: add prerequisiste check for aria suite lifecycle
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleYaml/config.PowerValidatedSolutions
  docs/documentation/functions/solutions/ila/index.md
  docs/documentation/functions/solutions/inv/index.md
  docs/documentation/functions/solutions/iom/index.md
  docs/documentation/functions/solutions/lcm.md
  docs/documentation/functions/solutions/lcm/Export-VrslcmJsonSpec.md
  docs/documentation/functions/solutions/lcm/Invoke-VrslcmDeployment.md
  docs/documentation/functions/solutions/lcm/Test-VrslcmPrerequisite.md
  docs/documentation/functions/solutions/lcm/index.md
  docs/documentation/functions/solutions/pca/index.md
  mkdocs.yml
Labels: documentation, feature, size/m, samples, cla-not-required

#604 chore: move config file
  PowerValidatedSolutions.psd1
  config.PowerValidatedSolutions
Labels: chore, cla-not-required

#606 feat: use config file for aria versions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  Update-vRSLCMPSPack.ps1
  config.PowerValidatedSolutions
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Import-vRSLCMPSPack.md
  docs/documentation/functions/solutions/lcm/Invoke-VrslcmUndoDeployment.md
  docs/documentation/functions/solutions/lcm/index.md
  mkdocs.yml
Labels: documentation, feature, size/xl, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#607 fix: pause for ps pack manual install
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/s, cla-not-required

#609 feat:add_export_root_ca_cmdlet
  CHANGELOG.md
  PowerValidatedSolutions.psm1
  docs/documentation/functions/certificates/Get-MscaRootCertificate.md
Labels: documentation, needs-review, cla-not-required

#611 feat: aria certs and version
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  config.PowerValidatedSolutions
  docs/documentation/functions/solutions/ila/Request-IlaMscaSignedCertificate.md
  docs/documentation/functions/solutions/ila/index.md
  docs/documentation/functions/solutions/iom/Request-IomMscaSignedCertificate.md
  docs/documentation/functions/solutions/iom/index.md
  docs/documentation/functions/solutions/pca/Request-PcaMscaSignedCertificate.md
  docs/documentation/functions/solutions/pca/index.md
  docs/documentation/functions/solutions/wsa/index.md
  mkdocs.yml
Labels: documentation, enhancement, needs-review, size/l, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#612 fix: aria suite datacenter creation error
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMDatacenter.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Invoke-vRSLCMUpgrade.md
  docs/documentation/functions/solutions/wsa/Invoke-GlobalWsaDeployment.md
  mkdocs.yml
Labels: bug, documentation, size/s, cla-not-required

#613 fix: add network adapter error output
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, needs-review, size/s, vvs/pdr, cla-not-required

#615 feat: enhance enable-vrlicontentpack
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, vvs/ila, cla-not-required

#616 fix: Get-vRAvRLIConfig cmdlet failing due to warning in the output
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, cla-not-required

#617 feat: add inv prerequsite option
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  config.PowerValidatedSolutions
  docs/documentation/functions/aria-suite/aria-operations-networks/Request-AriaNetworksToken.md
  docs/documentation/functions/solutions/inv/Test-InvPrerequisite.md
  docs/documentation/functions/solutions/inv/index.md
  mkdocs.yml
Labels: documentation, feature, size/s, cla-not-required, vvs/inv

#618 fix: deploy hrm photon appliance
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/s, cla-not-required, vvs/hrm

#619 feat: add inv cert creation
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/solutions/inv/Request-InvMscaSignedCertificate.md
  docs/documentation/functions/solutions/inv/index.md
  mkdocs.yml
Labels: documentation, feature, size/s, cla-not-required, vvs/inv

#620 feat: add end-to-end deployment for inv
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-operations-networks/Undo-AriaNetworksDeployment.md
  docs/documentation/functions/solutions/inv/Invoke-InvDeployment.md
  docs/documentation/functions/solutions/inv/Invoke-UndoInvDeployment.md
  docs/documentation/functions/solutions/inv/index.md
  mkdocs.yml
Labels: documentation, feature, size/m, cla-not-required, vvs/inv

#577 feat: add inv deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  config.PowerValidatedSolutions
  docs/documentation/functions/aria-suite/aria-operations-networks/Export-AriaNetworksJsonSpec.md
  docs/documentation/functions/aria-suite/aria-operations-networks/New-AriaNetworksDeployment.md
  mkdocs.yml
Labels: documentation, enhancement, cla-not-required, vvs/inv

#622 fix: testing aria networks deployment
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/m, cla-not-required, vvs/inv

#624 feat: enable eth1 for vsphere replication
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, size/m, vvs/pdr, cla-not-required

#625 chore: switch wsa content pack to manual
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/xs, chore, vvs/ila, cla-not-required

#626 fix: replication issues for pdr
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/l, vvs/pdr, cla-not-required

#630 fix: service account checks for multiple domains
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, vvs/iam, vvs/pca, vvs/ila, vvs/iom, cla-not-required, vvs/hrm, vvs/inv, vvs/cbw, vvs/ccm

#631 fix: issues with solution interop of aria operations for logs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-operations/Request-vROpsLogForwardingConfig.md
  docs/documentation/functions/solutions/hrm/Deploy-PhotonAppliance.md
  mkdocs.yml
Labels: bug, documentation, enhancement, vvs/iom, cla-not-required, vvs/hrm

#632 fix: remove portgroup from deploy-photonappliance
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/xs, cla-not-required, vvs/hrm

#635 fix: add-vrmsreplication to pass datastore name
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/vsphere-replication/Add-VrmsReplication.md
  docs/documentation/functions/vsphere-replication/Add-vSphereReplication.md
Labels: bug, documentation, enhancement, size/m, vvs/pdr, cla-not-required

#637 feat: add support for vcf 5.2
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  config.PowerValidatedSolutions
Labels: documentation, feature, vvs/pca, vvs/ila, vvs/iom, cla-not-required, vvs/inv

#638 fix: incorrect service accounts discovered for no access
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/iam, cla-not-required
