Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-09, with the labels that each got.

#734 feat: add support to remove standby mode configuration
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#737 chore: documentation updates
  CHANGELOG.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerStandby.md
  docs/documentation/functions/nsx/Undo-NsxtGlobalManagerStandby.md
  docs/documentation/functions/solutions/fed/index.md
  mkdocs.yml
Labels: documentation, chore, cla-not-required

#740 feat: pdr prerequisite check for nsx federation
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerConfig.md
Labels: documentation, enhancement, size/s, vvs/pdr, cla-not-required

#741 fix: typo on inv menu
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: size/xs, cla-not-required, vvs/inv

#744 feat: support to add and remove cross-instance t1 gateway
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#745 feat: support to connect cross instance segments to cross Instance t1 gw
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#746 chore: documentation updates
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/nsx/Add-NsxtGlobalManagerTier1Gateway.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerEdgeCluster.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerSegment.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerTier0Gateway.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerTier1Gateway.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerTier1LocaleServices.md
  docs/documentation/functions/nsx/Import-NsxtGlobalManagerLocation.md
  docs/documentation/functions/nsx/New-NsxtGlobalManagerTier1Gateway.md
  docs/documentation/functions/nsx/New-NsxtGlobalManagerTier1LocaleServices.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier1Gateway.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier1LocaleServices.md
  docs/documentation/functions/nsx/Set-NsxtGlobalManagerSegment.md
  docs/documentation/functions/nsx/Undo-NsxtGlobalManagerTier1Gateway.md
  docs/documentation/functions/nsx/Update-NsxtGlobalManagerSegment.md
  mkdocs.yml
Labels: documentation, feature, chore, cla-not-required

#747 fix: isolated domain issue for iam
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/xs, vvs/iam, cla-not-required

#748 feat: support to delete existing tier0 gateways in additional instances
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#749 chore: add missing documentation
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerTier0LocaleServices.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0Gateway.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0LocaleServices.md
  docs/documentation/functions/nsx/Undo-NsxtGlobalManagerTier0Gateway.md
  docs/documentation/functions/solutions/fed/index.md
  mkdocs.yml
Labels: documentation, needs-review, chore, cla-not-required

#751 fix: dns prereqs
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, needs-review, cla-not-required

#753 feat: support to delete existing tier0 gateway and export its network config
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, cla-not-required

#755 feat: enhance Add-WorkspaceOneDirectory
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/workspace-one-access/Get-WsaDirectory.md
Labels: documentation, enhancement, cla-not-required

#757 feat: Connect Additional Instances to Cross-Instance Tier-0 Gateway
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/nsx/Export-NsxtGlobalManagerTier0GatewayConfig.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0BgpNeighborConfig.md
  docs/documentation/functions/nsx/Remove-NsxtGlobalManagerTier0ServiceInterface.md
  docs/documentation/functions/nsx/Update-NsxtGlobalManagerTier1Gateway.md
  mkdocs.yml
Labels: documentation, needs-review, cla-not-required

#756 feat: support to connect additional vcf to cross instance tier0 gw
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: feature, cla-not-required

#759 feat: enhancements to Add-vRLISmtpConfiguration
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-operations-logs/Add-vRLISmtpConfiguration.md
Labels: documentation, enhancement, vvs/ila, cla-not-required

#760 feat: add support for vcf 521
  PowerValidatedSolutions.psd1
  config.PowerValidatedSolutions
Labels: feature, size/xs, cla-not-required

#761 feat: support to replace certificate on the NSX Global Manager.
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#762 feat: global manager cert replacement
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/nsx/Add-NsxtGlobalManagerCertificate.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerCertificate.md
  docs/documentation/functions/nsx/Get-NsxtGlobalManagerCertificateResult.md
  docs/documentation/functions/nsx/Import-NsxtGlobalManagerCertificate.md
  docs/documentation/functions/nsx/Install-NsxtGlobalManagerCertificate.md
  docs/documentation/functions/nsx/Test-NsxtGlobalManagerCertificate.md
  mkdocs.yml
Labels: documentation, feature, size/m, cla-not-required

#766 feat: nsx feration testing
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, needs-review, size/s, cla-not-required

#767 fix: address dns check issue with cbr
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, enhancement, size/s, cla-not-required, vvs/cbr

#768 chore(deps): bump `VMware.PowerCLI` from 13.2.1 to 13.3.0
  CHANGELOG.md
  config.PowerValidatedSolutions
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, dependencies, chore, cla-not-required

#769 chore(deps): bump `Import-Excel` from 7.8.5 to 7.8.9
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  config.PowerValidatedSolutions
  docs/index.md
Labels: documentation, needs-review, dependencies, chore, cla-not-required

#770 feat: remove breaks from add-networksegment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, size/s, vvs/dri, cla-not-required

#771 feat: nsx ova enhancement
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  config.PowerValidatedSolutions
Labels: documentation, enhancement, size/m, cla-not-required

#772 feat: enhance output and error handling for add-vropsadaptervcf
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, feature, size/m, vvs/iom, cla-not-required

#773 feat: enhancement to Add-vCenterGlobalPermission
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, vvs/iom, cla-not-required

#774 feat: enhancement to Set-WorkspaceOneNtpConfig
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, size/s, cla-not-required

#775 fix: pdr json generation issue
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, size/xs, vvs/pdr, cla-not-required

#776 chore: message improvements
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: chore

#777 chore: message improvements
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, chore, vvs/dri
