Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-02, with the labels that each got.

#490 fix: local account lockout policy
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, cla-not-required

#492 feat: oneclick for dri
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
  docs/documentation/functions/solutions/dri/Export-DriJsonSpec.md
  docs/documentation/functions/solutions/dri/Invoke-DriDeployment.md
  docs/documentation/functions/solutions/dri/Invoke-UndoDriDeployment.md
  docs/documentation/functions/solutions/dri/index.md
  mkdocs.yml
Labels: documentation, needs-review, size/l, vvs/dri, samples, cla-not-required

#494 chore(deps): bump powervcf from 2.4.0 to 2.4.1
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/index.md
  docs/snippets/install-module.ps1
Labels: documentation, dependencies, chore, cla-not-required

#495 chore(deps): support pwsh 7.2 and later
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  docs/index.md
  docs/install.md
Labels: documentation, needs-review, dependencies, chore, cla-not-required

#491 feat: add `Get-vRLSCMProductPassword`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductPassword.md
  mkdocs.yml
Labels: documentation, enhancement, cla-not-required

#497 chore: remove aria component versions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-automation/New-vRADeployment.md
Labels: documentation, needs-review, chore, cla-not-required

#498 feat: end-to-end testing of oneclicks
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, needs-review, size/m, cla-not-required

#499 feat: add support for creating vcf adapter in aria operations
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-operations/Add-vROPSAdapterVcf.md
  docs/documentation/functions/solutions/iom/index.md
  mkdocs.yml
Labels: documentation, feature, needs-review, size/m, vvs/iom, cla-not-required

#501 fix: Error while deploying a Supervisor
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, size/s, vvs/dri, cla-not-required

#504 feat: add oneclick for cbr
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/solutions/cbr/Export-CbrJsonSpec.md
  docs/documentation/functions/solutions/cbr/Invoke-CbrDeployment.md
  docs/documentation/functions/solutions/cbr/Invoke-UndoCbrDeployment.md
  docs/documentation/functions/solutions/cbr/index.md
  mkdocs.yml
Labels: documentation, feature, needs-review, size/m, cla-not-required, vvs/cbr

#505 feat: add oneclick for ccm
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/solutions/ccm/Export-CcmJsonSpec.md
  docs/documentation/functions/solutions/ccm/Invoke-CcmDeployment.md
  docs/documentation/functions/solutions/ccm/Invoke-UndoCcmDeployment.md
  docs/documentation/functions/solutions/ccm/index.md
  mkdocs.yml
Labels: documentation, feature, needs-review, size/m, cla-not-required, vvs/ccm

#507 feat: enhancements to message output for iam one-click
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, needs-review, size/s, vvs/iam, cla-not-required

#508 feat: enhancements to message output for dri one-click
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/dri, cla-not-required

#509 feat: enhance message output for ila one-click
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, vvs/ila, cla-not-required

#510 feat: enhance message output for hrm, cbw, cbr, ccm oneclick
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/s, cla-not-required, vvs/hrm, vvs/cbw, vvs/cbr, vvs/ccm

#511 feat: prepare for pdr oneclick
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/active-directory/Get-ADPrincipalGuid.md
  docs/documentation/functions/active-directory/Test-ADAuthentication.md
  docs/documentation/functions/site-recovery-manager/Add-RecoveryPlan.md
  docs/documentation/functions/solutions/pdr/Export-PdrJsonSpec.md
  docs/documentation/functions/solutions/pdr/index.md
  docs/documentation/functions/vsphere-replication/Add-EsxiVrmsVMkernelPort.md
  docs/documentation/functions/vsphere-replication/Add-vSphereReplication.md
  docs/documentation/functions/vsphere-replication/Connect-DRSolutionTovCenter.md
  docs/documentation/functions/vsphere/Move-VMtoFolder.md
  mkdocs.yml
Labels: documentation, feature, needs-review, size/l, vvs/pdr, cla-not-required

#506 fix: update role for aria automation orchestrator
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  vSphereRoles/aria-automation-orchestrator-vsphere-integration-7x.role
  vSphereRoles/aria-automation-orchestrator-vsphere-integration-8x.role
Labels: bug, documentation, cla-not-required

#516 feat: certificate managment of srm & vrms
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/site-recovery-manager/Add-ProtectionGroup.md
  docs/documentation/functions/site-recovery-manager/Add-RecoveryPlan.md
  docs/documentation/functions/site-recovery-manager/Add-SrmLicenseKey.md
  docs/documentation/functions/site-recovery-manager/Add-SrmMapping.md
  docs/documentation/functions/site-recovery-manager/Add-SrmProtectionGroup.md
  docs/documentation/functions/site-recovery-manager/Add-SrmRecoveryPlan.md
  docs/documentation/functions/site-recovery-manager/Add-SrmRecoveryPlanCalloutStep.md
  docs/documentation/functions/site-recovery-manager/Get-SrmVamiCertificate.md
  docs/documentation/functions/vsphere-replication/Get-VrmsVamiCertificate.md
Labels: documentation, size/s, vvs/pdr, cla-not-required

#517 feat: add pdr one-click
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/solutions/pdr/Invoke-PdrDeployment.md
  docs/documentation/functions/solutions/pdr/Invoke-UndoPdrDeployment.md
  docs/documentation/functions/solutions/pdr/index.md
  mkdocs.yml
Labels: documentation, feature, needs-review, size/l, vvs/pdr, cla-not-required

#519 feat: improve dns changes
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, size/m, vvs/pdr, cla-not-required

#520 chore: add .vscode settings
  .vscode/extensions.json
  .vscode/settings.json
Labels: needs-review, chore, cla-not-required

#521 feat: oneclick end-to-end testing
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, needs-review, size/m, vvs/pca, vvs/ila, vvs/iom, cla-not-required

#522 feat: add `vmid` option to `Get-vRSLCMProductDetails`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductDetails.md
Labels: documentation, enhancement, needs-review, cla-not-required
