Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-10, with the labels that each got.

#778 feat: enhanced ad group sync in wsa
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/active-directory/Get-ADPrincipalGuid.md
  docs/documentation/functions/workspace-one-access/Add-WorkspaceOneDirectory.md
  docs/documentation/functions/workspace-one-access/Add-WorkspaceOneDirectoryGroup.md
  docs/documentation/functions/workspace-one-access/Undo-WorkspaceOneDirectoryGroup.md
Labels: documentation, enhancement, vvs/pca, vvs/iom

#779 feat: enhance Add-vROPSAdapterVcf
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, vvs/iom

#780 chore(release): v2.12.0
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  docs/snippets/install-module.ps1
Labels: documentation, needs-review, chore

#781 chore: updated aria versions for older vcf releases
  PowerValidatedSolutions.psd1
  config.PowerValidatedSolutions
Labels: size/xs, chore, vvs/pca, vvs/iom, vvs/inv
