Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-03, with the labels that each got.

#503 feat: transition cetgenvvs to module
  CHANGELOG.md
  PowerValidatedSolutions.psm1
  docs/documentation/functions/certificates/Invoke-GenerateChainPem.md
  docs/documentation/functions/certificates/Invoke-GeneratePrivateKeyAndCsr.md
  docs/documentation/functions/certificates/Invoke-RequestSignedCertificate.md
Labels: documentation, cla-not-required

#523 feat: base64 encoded gh token
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-operations-logs/Enable-vRLIContentPack.md
  docs/documentation/functions/aria-suite/aria-operations-logs/Get-vRLIMarketplaceMetadata.md
Labels: documentation, enhancement, vvs/ila, cla-not-required

#525 feat: add `Copy-vSphereRole`
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/vsphere/Copy-vSphereRole.md
  docs/documentation/functions/vsphere/Get-DrsVmToVmGroup.md
  vSphereRoles/aria-automation-orchestrator-vsphere-integration-7x.role
  vSphereRoles/aria-automation-orchestrator-vsphere-integration-8x.role
  vSphereRoles/hcx-vsphere-integration-7x.role
  vSphereRoles/hcx-vsphere-integration-8x.role
Labels: documentation, enhancement, cla-not-required

#528 fix: resolved Invoke-GlobalWsaDeployment failing to resolve cross-region WSA FQDN
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, cla-not-required

#529 feat: update aria versions
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-automation/New-vRADeployment.md
  docs/documentation/functions/aria-suite/aria-operations-logs/New-vRLIDeployment.md
  docs/documentation/functions/aria-suite/aria-operations/New-vROPSDeployment.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Connect-vRSLCMUpgradeIso.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Request-vRSLCMProductBinary.md
Labels: documentation, enhancement, needs-review, cla-not-required

#532 docs: add certificate generation guide
  docs/documentation/user-guide/certificate-generation.md
  mkdocs.yml
Labels: documentation, needs-review, cla-not-required

#536 fix: update `Invoke-IomDeployment`
  CHANGELOG.md
  PowerValidatedSolutions.psm1
Labels: documentation, needs-review, size/s, vvs/iom, cla-not-required

#540 fix: add directory to global wsa
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, needs-review, size/s, cla-not-required

#541 fix: address error output for storage policy creation
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, enhancement, needs-review, vvs/dri, cla-not-required

#542 fix: Get-vRLIRole not returning data correctly
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/ila, cla-not-required

#543 feat: enhancement to Add-vRLIAuthenticationGroup
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, needs-review, size/s, vvs/ila, cla-not-required

#539 feat: verify integration aria automation integration
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-automation/Get-vRAIntegrationDetail.md
  docs/documentation/functions/aria-suite/aria-automation/Request-vRAToken.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Request-vRSLCMToken.md
  docs/documentation/functions/nsx/Add-CertToNsxCertificateStore.md
  docs/documentation/functions/nsx/New-NsxtSegment.md
  docs/documentation/functions/vsphere/Add-AntiAffinityRule.md
  docs/documentation/functions/vsphere/Add-ClusterGroup.md
  docs/documentation/functions/vsphere/Get-VMOvfProperty.md
  docs/documentation/functions/vsphere/Set-VMOvfProperty.md
Labels: documentation, cla-not-required

#545 feat: update wsa version
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, enhancement, vvs/iom, cla-not-required

#546 fix: udpate step to use Add-NsxtLdapRole
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/pca, cla-not-required

#547 fix: wrong -vraUser value in New-vRACloudAccount
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/pca, cla-not-required

#549 fix: Invoke-DriDeployment fails - parameter format
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, cla-not-required

#552 fix: incorrect input for add-namespace
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/dri, cla-not-required

#554 fix: addressing pipeline issues
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, vvs/iom, cla-not-required

#555 fix: enable vrli content pack
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: bug, documentation, size/s, vvs/ila, cla-not-required

#556 fix: bump vrlsmc version check
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, needs-review, size/s, cla-not-required
