Repository vmware/power-validated-solutions-for-cloud-foundation, pull requests merged in 2024-01, with the labels that each got.

#456 feat: add support for aria suite json output folder
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  SampleScripts/pca/pcaDeployAriaAutomation.ps1
Labels: documentation, enhancement, needs-review, size/l, vvs/pca, vvs/ila, vvs/iom, samples, cla-not-required

#457 feat: add functions to support aria suite lifecycle deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, cla-not-required

#458 fix: address oneclick issues
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, size/m, vvs/pca, cla-not-required

#459 feat: add oneclick for global wsa and aslcm
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, size/l, cla-not-required

#460 feat: add/remove nsxt principal identity
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, needs-review, size/m, vvs/iom, cla-not-required

#461 feat: add content pack removal
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, needs-review, size/m, vvs/ila, cla-not-required

#463 Fix address issues found during end to end testing
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, enhancement, feature, size/s, vvs/ila, cla-not-required

#464 docs: update for connected and disconnected
  docs/index.md
  docs/install.md
  docs/update.md
  mkdocs.yml
Labels: documentation, cla-not-required

#465 chore: update copyright
  LICENSE
  Makefile
  NOTICE
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  README.md
  SampleScripts/dri/driConfigureSupervisorCluster.ps1
  SampleScripts/dri/driDeployTanzuCluster.ps1
  SampleScripts/dri/driUndoDeployment.ps1
  SampleScripts/iam/iamSolutionInteroperability.ps1
  SampleScripts/ila/ilaSolutionInteroperability.ps1
  SampleScripts/ila/ilaUndoSolutionInteroperability.ps1
  SampleScripts/iom/iomSolutionInteroperability.ps1
Labels: documentation, needs-review, samples, cla-not-required

#466 Feature: Add support for SRM Protection Groups
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, size/l, vvs/pdr, cla-not-required

#467 docs: documentation updates
  docs/requirements.txt
  docs/snippets/install-module.ps1
  mkdocs.yml
Labels: documentation, cla-not-required

#469 feat: add support for mounting iso to aslcm
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/s, cla-not-required

#471 feat: add supporting functions for vrslcm upgrade
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, cla-not-required

#472 feat: add support for srm recovery plans
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, cla-not-required

#473 feat: add support for photon appliance deployment
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: documentation, feature, size/m, cla-not-required, vvs/hrm

#474 enhance: Support multiple VM target with Add-vSphereReplication and Undo
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
Labels: enhancement, vvs/pdr, cla-not-required

#480 docs: documentation updates
  docs/documentation/functions/solutions/inv/index.md
  docs/documentation/functions/solutions/iom/index.md
  docs/documentation/functions/solutions/lcm.md
  docs/documentation/functions/solutions/pdr/index.md
Labels: documentation, needs-review, cla-not-required

#481 chore: release v2.8.0
  CHANGELOG.md
Labels: documentation, needs-review, chore, cla-not-required

#479 feat: add aria suite lifecycle functions
  CHANGELOG.md
  PowerValidatedSolutions.psd1
  PowerValidatedSolutions.psm1
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMEnvironmentVMs.md
  docs/documentation/functions/aria-suite/aria-suite-lifecycle/Get-vRSLCMProductDetails.md
  mkdocs.yml
Labels: documentation, enhancement, needs-review, cla-not-required
